# Generated by Django 6.0.2 on 2026-03-04 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='engine',
            field=models.CharField(choices=[('unreal', 'Unreal Engine'), ('unity', 'Unity'), ('godot', 'Godot'), ('custom', 'Custom'), ('other', 'Other')], default='unity', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('pc', 'PC'), ('web', 'Web'), ('mobile', 'Mobile'), ('console', 'Console')], default='pc', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='trailer_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FollowDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_devs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('follower', 'developer')},
            },
        ),
    ]
