# Generated by Django 6.0.2 on 2026-03-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_engine_game_platform_game_trailer_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
