# Generated by Django 6.0.2 on 2026-03-09 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gamereview',
            index=models.Index(fields=['user', '-created_at'], name='games_gamer_user_id_1069a5_idx'),
        ),
        migrations.AddIndex(
            model_name='gamereview',
            index=models.Index(fields=['game', '-created_at'], name='games_gamer_game_id_58993d_idx'),
        ),
    ]
