# Generated by Django 6.0.2 on 2026-03-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_company_logo_job_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
