# Generated by Django 6.0.2 on 2026-03-09 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_view_count_alter_job_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', '-applied_at'], name='jobs_applic_job_id_020f92_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', '-applied_at'], name='jobs_applic_applica_f72c6e_idx'),
        ),
    ]
