# Generated by Django 6.0.2 on 2026-03-07 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_engine_game_platform_game_trailer_url_and_more'),
        ('marketplace', '0004_alter_wishlist_options_collection_collectionitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('trending', 'Trending Now'), ('new', 'New Releases'), ('popular_category', 'Popular in Category'), ('staff_pick', 'Staff Picks'), ('seasonal', 'Seasonal')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('banner_image', models.CharField(blank=True, max_length=500)),
                ('background_color', models.CharField(blank=True, max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.asset')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'ordering': ['order', '-views'],
            },
        ),
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_searches', models.IntegerField(default=0)),
                ('unique_searchers', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('click_through_rate', models.FloatField(default=0)),
                ('top_queries', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='SearchFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(choices=[('category', 'Category'), ('price_range', 'Price Range'), ('rating', 'Rating'), ('tag', 'Tag'), ('format', 'Format'), ('creator', 'Creator'), ('license', 'License')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('asset_count', models.IntegerField(default=0)),
                ('game_count', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon', max_length=50)),
                ('color', models.CharField(blank=True, help_text='Hex color for UI', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['filter_type', 'order'],
                'unique_together': {('filter_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('search_type', models.CharField(choices=[('assets', 'Assets'), ('games', 'Games')], max_length=20)),
                ('query_text', models.CharField(max_length=500)),
                ('filters', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False, help_text='Share search with community')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_count', models.IntegerField(default=0)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=500)),
                ('search_type', models.CharField(choices=[('assets', 'Assets'), ('games', 'Games'), ('creators', 'Creators'), ('global', 'Global')], max_length=20)),
                ('results_count', models.IntegerField(default=0)),
                ('filters_applied', models.JSONField(default=dict, help_text='Filters used: category, price_range, rating_min, etc.')),
                ('clicked_result', models.BooleanField(default=False, help_text='User clicked on a search result')),
                ('click_position', models.IntegerField(blank=True, help_text='Position of clicked result (0-indexed)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, help_text='User IP for anonymous tracking', max_length=45)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='marketplace_user_id_0dcd99_idx'), models.Index(fields=['query_text', 'search_type'], name='marketplace_query_t_2b24ba_idx'), models.Index(fields=['created_at'], name='marketplace_created_42eb41_idx')],
            },
        ),
        migrations.CreateModel(
            name='SimilarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0)),
                ('matching_tags', models.IntegerField(default=0)),
                ('matching_category', models.BooleanField(default=False)),
                ('collaborator_bought', models.BooleanField(default=False)),
                ('rank', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('similar_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='found_similar_in_assets', to='marketplace.asset')),
                ('similar_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='found_similar_in_games', to='games.game')),
                ('source_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_assets', to='marketplace.asset')),
            ],
            options={
                'ordering': ['-similarity_score'],
                'unique_together': {('source_asset', 'similar_asset'), ('source_asset', 'similar_game')},
            },
        ),
        migrations.CreateModel(
            name='TrendingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('asset', 'Asset'), ('game', 'Game')], max_length=10)),
                ('score', models.FloatField(default=0, help_text='Composite trending score')),
                ('views_30d', models.IntegerField(default=0)),
                ('purchases_30d', models.IntegerField(default=0)),
                ('likes_30d', models.IntegerField(default=0)),
                ('rating_avg', models.FloatField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(choices=[('today', 'Today'), ('week', 'This Week'), ('month', 'This Month'), ('all_time', 'All Time')], default='month', max_length=20)),
                ('ranking', models.IntegerField(default=0, help_text='Position in trending list')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trending_records', to='marketplace.asset')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trending_records', to='games.game')),
            ],
            options={
                'ordering': ['period', 'ranking'],
                'indexes': [models.Index(fields=['period', 'ranking'], name='marketplace_period_d67bf6_idx'), models.Index(fields=['score', '-calculated_at'], name='marketplace_score_9bbd7f_idx')],
                'unique_together': {('item_type', 'asset', 'period'), ('item_type', 'game', 'period')},
            },
        ),
    ]
