# Generated by Django 6.0.2 on 2026-03-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_discoverycard_searchanalytics_searchfilter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
