# Generated by Django 6.0.2 on 2026-03-09 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_asset_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['buyer', '-purchased_at'], name='marketplace_buyer_i_efdc4f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['asset', '-purchased_at'], name='marketplace_asset_i_a380a5_idx'),
        ),
    ]
