# Generated by Django 6.0.2 on 2026-03-07 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('games', '0002_game_engine_game_platform_game_trailer_url_and_more'),
        ('marketplace', '0004_alter_wishlist_options_collection_collectionitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('milestone', 'Milestone'), ('badge', 'Badge'), ('award', 'Award'), ('certification', 'Certification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🏆', help_text='Emoji or icon class', max_length=50)),
                ('color', models.CharField(default='#f59e0b', help_text='Badge color hex code', max_length=7)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_rare', models.BooleanField(default=False, help_text='Special/rare achievement')),
                ('progress_current', models.IntegerField(default=0)),
                ('progress_target', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-is_rare', '-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='CreatorPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, help_text='Make portfolio visible to everyone')),
                ('custom_url', models.SlugField(blank=True, help_text='Custom portfolio URL', max_length=100, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='Short professional tagline', max_length=200)),
                ('specialties', models.JSONField(default=list, help_text='List of specialties/focus areas')),
                ('years_experience', models.IntegerField(default=0)),
                ('cover_image', models.CharField(blank=True, max_length=500)),
                ('primary_color', models.CharField(default='#0db9f2', help_text='Hex color code', max_length=7)),
                ('total_views', models.IntegerField(default=0)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_downloads', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('featured_by_platform', models.BooleanField(default=False)),
                ('verified_creator', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-total_views'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('asset', 'Asset'), ('game', 'Game')], max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = earlier)')),
                ('featured_note', models.TextField(blank=True, help_text='Why this work is special')),
                ('is_showcase', models.BooleanField(default=False, help_text='Pin to top of portfolio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('marketplace_notifications', models.BooleanField(default=True)),
                ('social_notifications', models.BooleanField(default=True)),
                ('job_notifications', models.BooleanField(default=True)),
                ('mentorship_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_time_on_page', models.IntegerField(default=0, help_text='Average seconds spent')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📦', help_text='Section icon emoji', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('author_title', models.CharField(blank=True, help_text="e.g., 'CEO at Company'", max_length=200)),
                ('author_avatar', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(help_text='The testimonial text')),
                ('rating', models.IntegerField(default=5, help_text='Rating out of 5')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('review', 'Review'), ('asset_approved', 'Asset Approved'), ('asset_rejected', 'Asset Rejected'), ('price_change', 'Price Change'), ('comment', 'Comment'), ('follow', 'Follow'), ('like', 'Like'), ('mention', 'Mention'), ('job_application', 'Job Application'), ('job_offer', 'Job Offer'), ('mentorship_request', 'Mentorship Request'), ('session_scheduled', 'Session Scheduled'), ('competition_submission', 'Competition Submission'), ('competition_result', 'Competition Result'), ('payment', 'Payment'), ('moderation', 'Moderation'), ('system', 'System'), ('welcome', 'Welcome')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read'], name='core_notifi_user_id_4a178e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='core_notifi_user_id_7862c3_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='core_notifi_notific_cbfe88_idx'),
        ),
        migrations.AddField(
            model_name='creatorportfolio',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_portfolio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achievement',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.creatorportfolio'),
        ),
        migrations.AddField(
            model_name='featureditem',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_in', to='marketplace.asset'),
        ),
        migrations.AddField(
            model_name='featureditem',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_in', to='games.game'),
        ),
        migrations.AddField(
            model_name='featureditem',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_items', to='core.creatorportfolio'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolioanalytics',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.creatorportfolio'),
        ),
        migrations.AddField(
            model_name='portfoliosection',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.creatorportfolio'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='core.creatorportfolio'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='related_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.asset'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='related_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.game'),
        ),
        migrations.AddIndex(
            model_name='creatorportfolio',
            index=models.Index(fields=['is_public', '-total_views'], name='core_creato_is_publ_9fedcf_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorportfolio',
            index=models.Index(fields=['custom_url'], name='core_creato_custom__db1148_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featureditem',
            unique_together={('portfolio', 'asset'), ('portfolio', 'game')},
        ),
        migrations.AddIndex(
            model_name='portfolioanalytics',
            index=models.Index(fields=['portfolio', '-date'], name='core_portfo_portfol_37b2f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioanalytics',
            unique_together={('portfolio', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='portfoliosection',
            unique_together={('portfolio', 'title')},
        ),
    ]
