# Generated by Django 6.0.2 on 2026-03-07 21:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_achievement_creatorportfolio_featureditem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_asset_types', models.JSONField(default=list)),
                ('preferred_game_genres', models.JSONField(default=list)),
                ('preferred_job_types', models.JSONField(default=list)),
                ('preferred_software', models.JSONField(default=list)),
                ('enable_recommendations', models.BooleanField(default=True)),
                ('include_social_signals', models.BooleanField(default=True)),
                ('include_trending', models.BooleanField(default=True)),
                ('max_price_preference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('blocked_categories', models.JSONField(default=list)),
                ('share_activity_for_recommendations', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_sellers', models.ManyToManyField(blank=True, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('asset', 'Asset'), ('game', 'Game'), ('job', 'Job')], max_length=20)),
                ('content_id', models.IntegerField()),
                ('score', models.FloatField()),
                ('score_components', models.JSONField(default=dict)),
                ('recommendation_reason', models.CharField(max_length=255)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'content_type', 'score'], name='core_recomm_user_id_7d2744_idx'), models.Index(fields=['content_type', 'content_id'], name='core_recomm_content_64e0cf_idx'), models.Index(fields=['last_calculated'], name='core_recomm_last_ca_b6a898_idx')],
                'unique_together': {('user', 'content_type', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('search_type', models.CharField(choices=[('asset', 'Asset Search'), ('game', 'Game Search'), ('job', 'Job Search'), ('user', 'User Search'), ('general', 'General Search')], max_length=20)),
                ('results_count', models.IntegerField(default=0)),
                ('clicked_result_id', models.IntegerField(blank=True, null=True)),
                ('clicked_result_position', models.IntegerField(blank=True, null=True)),
                ('filters_used', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_search_user_id_287ae0_idx'), models.Index(fields=['search_type', 'query'], name='core_search_search__5a800f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('download', 'Download'), ('purchase', 'Purchase'), ('like', 'Like'), ('share', 'Share'), ('search_result_click', 'Search Result Click')], max_length=30)),
                ('content_type', models.CharField(choices=[('asset', 'Asset'), ('game', 'Game'), ('job', 'Job'), ('user_profile', 'User Profile'), ('post', 'Post')], max_length=20)),
                ('content_id', models.IntegerField()),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('interaction_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('search_query', models.CharField(blank=True, max_length=255)),
                ('referrer_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_userin_user_id_47227b_idx'), models.Index(fields=['content_type', 'content_id'], name='core_userin_content_4c27aa_idx'), models.Index(fields=['interaction_type'], name='core_userin_interac_cb083c_idx'), models.Index(fields=['user', 'content_type', 'interaction_type'], name='core_userin_user_id_313dbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='WishlistExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('game', 'Game'), ('job', 'Job')], max_length=20)),
                ('content_id', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('price_alert_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'content_type'], name='core_wishli_user_id_a8934e_idx'), models.Index(fields=['content_type', 'content_id'], name='core_wishli_content_890888_idx')],
                'unique_together': {('user', 'content_type', 'content_id')},
            },
        ),
    ]
