# Generated by Django 6.0.2 on 2026-03-09 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userpreference_recommendationscore_searchhistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('asset', 'Asset Review'), ('game', 'Game Review'), ('mentor', 'Mentor Review')], max_length=20)),
                ('review_id', models.IntegerField()),
                ('reason', models.CharField(choices=[('fake_review', 'Fake/Fraudulent Review'), ('harassment', 'Harassment/Spam'), ('competitor_sabotage', 'Competitor Sabotage'), ('inaccurate', 'Factually Inaccurate'), ('inappropriate', 'Inappropriate Content'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('evidence_url', models.URLField(blank=True, help_text='Link to evidence')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('upheld', 'Upheld (Review Kept)'), ('reversed', 'Reversed (Review Removed)'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('moderator_decision', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('disputer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_disputes', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('creator', 'Creator'), ('developer', 'Developer'), ('recruiter', 'Recruiter'), ('mentor', 'Mentor')], max_length=20)),
                ('current_tier', models.CharField(default='novice', max_length=20)),
                ('current_score', models.FloatField(default=0)),
                ('progress_percent', models.IntegerField(default=0)),
                ('next_milestone_score', models.FloatField(default=10)),
                ('milestones', models.JSONField(blank=True, default=list)),
                ('tier_achieved_at', models.DateTimeField(auto_now_add=True)),
                ('last_progress_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-current_score'],
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='RoleVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('creator_portfolio', 'Creator Portfolio'), ('developer_game', 'Published Game'), ('recruiter_company', 'Company Registration'), ('recruiter_background', 'Background Check'), ('mentor_credentials', 'Teaching Credentials'), ('mentor_experience', 'Industry Experience')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('submission_url', models.URLField(blank=True)),
                ('submission_data', models.JSONField(blank=True, default=dict)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('user', 'verification_type')},
            },
        ),
    ]
