# Generated by Django 6.0.2 on 2026-03-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='resume',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='available_for_mentorship',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_size',
            field=models.CharField(blank=True, help_text='e.g., 1-10, 11-50, 51-200', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expertise_areas',
            field=models.JSONField(blank=True, default=list, help_text='Areas of expertise for mentoring'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='game_engines',
            field=models.JSONField(blank=True, default=list, help_text='Unity, Unreal, Godot, etc.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hiring_for',
            field=models.JSONField(blank=True, default=list, help_text='Roles actively hiring for'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='programming_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='software_expertise',
            field=models.JSONField(blank=True, default=list, help_text="Software tools you're proficient in"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialization',
            field=models.CharField(blank=True, help_text='e.g., 3D Artist, VFX Designer, Sound Designer', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teaching_experience',
            field=models.IntegerField(default=0, help_text='Years of teaching/mentoring'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_game_dev',
            field=models.IntegerField(default=0, help_text='Years in game development'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('CREATOR', 'Creator'), ('DEVELOPER', 'Developer'), ('RECRUITER', 'Recruiter'), ('MENTOR', 'Mentor')], default='CREATOR', max_length=20),
        ),
    ]
