# Generated by Django 6.0.2 on 2026-03-09 20:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_user_type_remove_userprofile_resume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('badge_type', models.CharField(choices=[('creator', 'Creator'), ('developer', 'Developer'), ('recruiter', 'Recruiter'), ('mentor', 'Mentor'), ('community', 'Community'), ('achievement', 'Achievement')], max_length=20)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji or icon class', max_length=50)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('required_score', models.IntegerField(default=0)),
                ('required_count', models.IntegerField(default=0, help_text='Required number of actions')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assets_purchased',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='creator_sales_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='creator_score',
            field=models.FloatField(default=0, help_text='Asset quality, sales, reviews'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='creator_total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='developer_games_published',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='developer_score',
            field=models.FloatField(default=0, help_text='Game quality, downloads, community engagement'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='developer_total_downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='jobs_applied',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mentor_score',
            field=models.FloatField(default=0, help_text='Teaching quality, student feedback'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mentor_sessions_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mentor_students_taught',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mentorship_sessions_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_role',
            field=models.CharField(choices=[('USER', 'User/Player'), ('CREATOR', 'Creator'), ('DEVELOPER', 'Developer'), ('RECRUITER', 'Recruiter'), ('MENTOR', 'Mentor')], default='USER', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recruiter_active_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recruiter_score',
            field=models.FloatField(default=0, help_text='Hiring success, employer reviews'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recruiter_successful_hires',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondary_roles',
            field=models.JSONField(blank=True, default=list, help_text='Additional roles this user performs'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('USER', 'User/Player'), ('CREATOR', 'Creator'), ('DEVELOPER', 'Developer'), ('RECRUITER', 'Recruiter'), ('MENTOR', 'Mentor')], default='USER', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_role', models.CharField(max_length=20)),
                ('consumer_role', models.CharField(default='USER', max_length=20)),
                ('service_type', models.CharField(choices=[('asset_sale', 'Asset Sale'), ('game_download', 'Game Download'), ('job_application', 'Job Application'), ('mentorship_session', 'Mentorship Session'), ('game_review', 'Game Review'), ('asset_review', 'Asset Review')], max_length=30)),
                ('service_name', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rating', models.IntegerField(blank=True, help_text='1-5 stars', null=True)),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_consumed', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_provided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Flow',
                'verbose_name_plural': 'Service Flows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'User/Player'), ('CREATOR', 'Creator'), ('DEVELOPER', 'Developer'), ('RECRUITER', 'Recruiter'), ('MENTOR', 'Mentor')], max_length=20)),
                ('score', models.FloatField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('five_star_count', models.IntegerField(default=0)),
                ('services_provided', models.IntegerField(default=0)),
                ('services_consumed', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('community_engagement', models.IntegerField(default=0)),
                ('verified_badge', models.BooleanField(default=False)),
                ('trust_level', models.IntegerField(default=1, help_text='1-5, based on history and reputation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_reputations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Reputation',
                'verbose_name_plural': 'Role Reputations',
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='RoleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_reviewed', models.CharField(choices=[('RECRUITER', 'Recruiter'), ('MENTOR', 'Mentor')], max_length=20)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review_text', models.TextField()),
                ('professionalism', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('communication', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('would_recommend', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Review',
                'verbose_name_plural': 'Role Reviews',
                'unique_together': {('reviewer', 'reviewed_user', 'role_reviewed')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('displayed', models.BooleanField(default=True, help_text='Show on profile')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
