# Generated by Django 6.0.2 on 2026-03-09 21:19

from django.db import migrations, models


def migrate_user_role_to_vector(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    RoleReputation = apps.get_model('users', 'RoleReputation')
    ServiceFlow = apps.get_model('users', 'ServiceFlow')

    UserProfile.objects.filter(primary_role='USER').update(primary_role='VECTOR')
    UserProfile.objects.filter(role='USER').update(role='VECTOR')
    RoleReputation.objects.filter(role='USER').update(role='VECTOR')
    ServiceFlow.objects.filter(consumer_role='USER').update(consumer_role='VECTOR')


def reverse_vector_to_user(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    RoleReputation = apps.get_model('users', 'RoleReputation')
    ServiceFlow = apps.get_model('users', 'ServiceFlow')

    UserProfile.objects.filter(primary_role='VECTOR').update(primary_role='USER')
    UserProfile.objects.filter(role='VECTOR').update(role='USER')
    RoleReputation.objects.filter(role='VECTOR').update(role='USER')
    ServiceFlow.objects.filter(consumer_role='VECTOR').update(consumer_role='USER')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_badge_userprofile_assets_purchased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolereputation',
            name='role',
            field=models.CharField(choices=[('VECTOR', 'Vector Member'), ('CREATOR', 'Creator'), ('DEVELOPER', 'Developer'), ('RECRUITER', 'Recruiter'), ('MENTOR', 'Mentor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceflow',
            name='consumer_role',
            field=models.CharField(default='VECTOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='primary_role',
            field=models.CharField(choices=[('VECTOR', 'Vector Member'), ('CREATOR', 'Creator'), ('DEVELOPER', 'Developer'), ('RECRUITER', 'Recruiter'), ('MENTOR', 'Mentor')], default='VECTOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('VECTOR', 'Vector Member'), ('CREATOR', 'Creator'), ('DEVELOPER', 'Developer'), ('RECRUITER', 'Recruiter'), ('MENTOR', 'Mentor')], default='VECTOR', max_length=20),
        ),
        migrations.RunPython(migrate_user_role_to_vector, reverse_vector_to_user),
    ]
