# Generated by Django 6.0.2 on 2026-03-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_rolereputation_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_view_as_role',
            field=models.CharField(blank=True, choices=[('VECTOR', 'Vector Member'), ('CREATOR', 'Creator'), ('DEVELOPER', 'Developer'), ('RECRUITER', 'Recruiter'), ('MENTOR', 'Mentor')], max_length=20, null=True),
        ),
    ]
