# Generated by Django 6.0.2 on 2026-03-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_admin_view_as_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='creator_tier',
            field=models.CharField(choices=[('novice', 'Novice'), ('apprentice', 'Apprentice'), ('professional', 'Professional'), ('expert', 'Expert'), ('elite', 'Elite')], default='novice', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='creator_verified',
            field=models.BooleanField(default=False, help_text='Portfolio verified'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='developer_tier',
            field=models.CharField(choices=[('novice', 'Novice'), ('apprentice', 'Apprentice'), ('professional', 'Professional'), ('expert', 'Expert'), ('elite', 'Elite')], default='novice', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='developer_verified',
            field=models.BooleanField(default=False, help_text='Game published + verified'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mentor_tier',
            field=models.CharField(choices=[('novice', 'Novice'), ('apprentice', 'Apprentice'), ('professional', 'Professional'), ('expert', 'Expert'), ('elite', 'Elite')], default='novice', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mentor_verified',
            field=models.BooleanField(default=False, help_text='Credentials verified'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recruiter_tier',
            field=models.CharField(choices=[('novice', 'Novice'), ('apprentice', 'Apprentice'), ('professional', 'Professional'), ('expert', 'Expert'), ('elite', 'Elite')], default='novice', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recruiter_verified',
            field=models.BooleanField(default=False, help_text='Company verified + licensed'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='admin_view_as_role',
            field=models.CharField(blank=True, choices=[('PLAYER', 'Player'), ('CREATOR', 'Creator'), ('DEVELOPER', 'Developer'), ('RECRUITER', 'Recruiter'), ('MENTOR', 'Mentor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='primary_role',
            field=models.CharField(choices=[('PLAYER', 'Player'), ('CREATOR', 'Creator'), ('DEVELOPER', 'Developer'), ('RECRUITER', 'Recruiter'), ('MENTOR', 'Mentor')], default='PLAYER', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('PLAYER', 'Player'), ('CREATOR', 'Creator'), ('DEVELOPER', 'Developer'), ('RECRUITER', 'Recruiter'), ('MENTOR', 'Mentor')], default='PLAYER', max_length=20),
        ),
    ]
